# -*- coding: utf-8 -*-
"""BigDataL2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R2FVY14EpMvqoiTdKwb7lfKqhi9_CUNt

###Bar Graph
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.plot([1,2,3,4,5],[2,4,6,8,10],"r*")
plt.show

plt.plot([1,2,3,4,5],[2,4,6,8,10])
plt.title("graphicl analysis")
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.show

t = np.arange(0.,5.,0.2)
t

x1 = [5,8,10]
y1 = [12,6,16]
x2 = [6,9,11]
y2 = [6,15,17]
plt.plot(x1,y1,"red",label="age",linewidth=5)
plt.plot(x2,y2,"blue",label="income",linewidth=4)
plt.legend()
plt.grid(True,color="lightgrey")
plt.show

x1 = [5,8,10]
y1 = [12,6,16]
x2 = [6,9,11]
y2 = [6,15,17]
plt.bar(x1,y1,color="blue")
plt.show
plt.bar(x2,y2,color="red")
plt.show

"""##Scatter Plot"""

x = [6,9,11,14,20,24,30]
y = [6,15,17,22,30,37,44]
plt.scatter(x,y)
plt.show()

"""##Catagrical Graph"""

x = [100,200,300,400]
y = [10,20,30,40]
plt.figure(figsize=(9,3))
plt.subplot(131)
plt.bar(x,y)
plt.subplot(132)
plt.scatter(x,y)
plt.subplot(133)
plt.plot(x,y)

data = pd.read_csv("/content/drive/MyDrive/cafe.csv")
data.head(10)

add = data["Address"].head(10)
mon = data["AFF-Mon"].head(10)
plt.bar(add,mon)
plt.xticks(add,('a','b','c','d','e'))

plt.scatter(add,mon)
plt.xticks(rotation=90)
plt.savefig("/content/drive/MyDrive/mygraph.png")
plt.show()

plt.savefig("/content/drive/MyDrive/mygraph.png")
plt.show()

import folium as f

f.Map(location=[27.210496,75.699617])

